name: check
on:
  push: 
    paths:
    - 'converter-examples/**'
    
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: volta list
      - run: npm ci
      - run: npm run check
